services:
  selenium:
    image: selenium/standalone-chrome-firefox:4.21.0-20240604
    ports:
      - 4444:4444

env:
  GRID_URL: "http://localhost:4444/wd/hub"

steps:
  - uses: actions/checkout@v4

  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: "3.10"

  - name: Install Dependencies
    run: |
      pip install -r requirements.txt

  - name: Run Tests (Chrome)
    run: pytest -vs --browser=chrome

  - name: Run Tests (Firefox)
    run: pytest -vs --browser=firefox
